name: confenx

channels:
  - conda-forge

dependencies:
  - python=3.11
  - fenics-dolfinx=0.9.0
  - mpich
  - scipy
  - matplotlib
  - jupyter
  - ipykernel
  - pip

  - pip:
      - pyvista
      - meshio
      - pygmsh
      - gmsh